### ISSUE TITLE
[Errno 2] No such file or directory: 'ng'

### ISSUE THREAD

**Issue by aramisnegron** [4ern/angular-cli-for-sublime-text#2]
Tried it in different computers and still getting the following error:
[Errno 2] No such file or directory: 'ng'
[cmd: ['ng', 'g', 'class', 'test']]
[dir: /Users/username/my-project]
[path: /usr/bin:/bin:/usr/sbin:/sbin]

**Comment by 4ern** [comment]
Have you install https://github.com/angular/angular-cli ?

**Comment by aramisnegron** [comment]
Thank you for replying. 
I found a fix by adding an attribute("path": '/usr/local/bin/') to the Angular CLI.py after line 63. Now its working perfectly.
Thanks again.
